version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    reviewers:
      - "prakashguy50"

  - package-ecosystem: "pip"
    directory: "/ml-pipeline"
    schedule:
      interval: "monthly"