# .github/dependabot.yml

version: 2
updates:
  # Update Maven dependencies (Java)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "YOUR_GITHUB_USERNAME"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    labels:
      - "dependencies"
      - "java"

  # Update Python dependencies (ML pipeline)
  - package-ecosystem: "pip"
    directory: "/ml-pipeline/model_training"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "YOUR_GITHUB_USERNAME"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "python"
      - "ml"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "11:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"

  # Update Docker containers
  - package-ecosystem: "docker"
    directory: "/config/docker"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"