- name: Build and Push API Docker Image to Artifact Registry
  run: |
    gcloud builds submit D:/Prakash/Projects/healthvision-ai-gcp/ \
      --config=D:/Prakash/Projects/healthvision-ai-gcp/config/docker/cloudbuild.api.yaml
