services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: healthvision
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    image: ghcr.io/prakashguy50/healthvision-api-gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://image-service:8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"