version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthvision
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  api-gateway:
    image: gcr.io/${GCP_PROJECT_ID}/api-gateway:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthvision
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      
  image-service:
    image: gcr.io/${GCP_PROJECT_ID}/image-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      GCS_BUCKET: healthvision-dev-data
    depends_on:
      - api-gateway
      
volumes:
  pgdata: