apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: image-service
        image: gcr.io/PROJECT_ID/image-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: gcs.bucket
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  gcs.bucket: "healthvision-data-bucket"
  pubsub.topic: "image-processed"# Trigger deployment Thu Mar 27 18:01:32 IST 2025
