spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/images/**
        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/api/llm/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always