apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: healthvision-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: healthvision-vs
spec:
  hosts:
  - "*"
  gateways:
  - healthvision-gateway
  http:
  - match:
    - uri:
        prefix: /api/images
    route:
    - destination:
        host: image-service
        port:
          number: 8080
  - match:
    - uri:
        prefix: /api/llm
    route:
    - destination:
        host: llm-service
        port:
          number: 8080