name: GKE Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'config/k8s/**'
      - '.github/workflows/cd-gke.yml'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials healthvision-cluster \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }}
          
    - name: Deploy to GKE
      run: |
        kubectl apply -f config/k8s/ -R
        kubectl rollout status deployment/image-service
        kubectl rollout status deployment/api-gateway