name: Java CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'services/**'
      - '.github/workflows/ci-java.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn -B test
      
    - name: Build Docker images
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest -f config/docker/Dockerfile.api --build-arg JAR_FILE=services/api-gateway/target/*.jar .
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-service:latest -f config/docker/Dockerfile.api --build-arg JAR_FILE=services/image-service/target/*.jar .
        
    - name: Push to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gateway:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-service:latest