name: ML CI

on:
  push:
    branches: [ main ]
    paths:
      - 'ml-pipeline/**'
      - '.github/workflows/ci-ml.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r ml-pipeline/requirements.txt
        pip install pytest
        
    - name: Run training
      run: |
        python ml-pipeline/scripts/train_model.py \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --bucket=gs://${{ secrets.GCP_PROJECT_ID }}-ml-data
          
    - name: Upload model
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ml-pipeline/model/
        destination: gs://${{ secrets.GCP_PROJECT_ID }}-ml-data/models/